### ISSUE TITLE
Question: Is this compatible with Laravel Pagination API

### ISSUE THREAD

**Issue by anburocky3** [uwla/vue-data-table#40] opened 2021-10-28 12:44 UTC

**Comment by AndreSouzaAbreu** [comment] 2021-11-08 14:54
Hello.
This packages works only on the client side. I don't know the Laravel Pagination API, but it is very likely it is not
compatible with it.

It is a very interesting idea to make it compatible with Laravel API since Laravel is very popular (I myself use it) and
there are already some users who wan't to use it on the server side.

This will be a feature for  the future

**Comment by anburocky3** [comment] 2021-11-08 20:26
@AndreSouzaAbreu What I'm trying to say is:

If I use Laravel Pagination in a laravel, can we use those pagination JSON data with this (yours) vue-data-table (which is a client)

Or do we need to construct our data according to your plugin..

It would be great if you made this work. Since mostly vue communities are using laravel as their backend, it would be helpful for them.

**Comment by AndreSouzaAbreu** [comment] 2021-11-12 15:59
I use laravel as the backend of my projects and Vue as frontend. I do get the
JSON data from Laravel API and the display it with VueDataTable. There is an
`prop` called `defaultPerPage` and `perPageSizes` that tells VueDataTable the
current page and the entries per page shown to the user. It's pretty easy to
use with data from any API, including Laravel. You just have to pass the
current page, and the amount of entries per page, to the Vue component. Since
you have access to the JSON from your backend, the only thing you need to do
is extract the information from the JSON, which should be straightforward,
just get the property of an object.

If you need specific help with it, I can help you. But, as I said, it is just
pass the pagination settings as props to the component.

**Comment by anburocky3** [comment] 2021-11-14 12:35
@AndreSouzaAbreu Thanks for the good start. Can we add any gist of this, to see it in action.

We can add it to documentation as well. Help me with the gist of integrating laravel pagination with this plugin.

Regards.

**Comment by AndreSouzaAbreu** [comment] 2021-11-14 13:35
Yes, we can add a gist and add it to the documentation.

Do you have a gist ready? Or maybe, some sample project on CodeSandbox or
similar ?  I have two demos of VueDataTable on CodeSandbox (I plan to add
more demos during my vacations).  If you wish, you can create some demo of a
Laravel+Vue project there and send me the link. I will then help you set up
VueDataTable for pagination.

**Comment by anburocky3** [comment] 2021-11-17 20:39
> Yes, we can add a gist and add it to the documentation.
> 
> Do you have a gist ready? Or maybe, some sample project on CodeSandbox or similar ? I have two demos of VueDataTable on CodeSandbox (I plan to add more demos during my vacations). If you wish, you can create some demo of a Laravel+Vue project there and send me the link. I will then help you set up VueDataTable for pagination.

Can i create a example app in laravel with some pagination and another repository with vue frontend? And can you help me in setting up it? We can add those example apps in your documentation. 

😊 Looking forward.

**Comment by anburocky3** [comment] 2021-11-25 13:15
@AndreSouzaAbreu Still waiting for your reply.

**Comment by AndreSouzaAbreu** [comment] 2021-11-26 13:16
Yes, you can create a sample app for that for testing. I can help set up the client side for pagination

**Comment by anburocky3** [comment] 2021-12-02 02:37
**Here is my sample backend:** 

Backend Repo: https://github.com/anburocky3/laravel-datatables-demo/

Sample API with Laravel Pagination: https://anburocky3.github.io/laravel-datatables-demo/data/articles.json

**Comment by AndreSouzaAbreu** [comment] 2021-12-14 01:22
THank you very much.

I'll look at it in a couple of days, because right now I'm busy

**Comment by AndreSouzaAbreu** [comment] 2022-01-07 15:27
just to update you, now I'mma dedicate time for this issue

**Comment by AndreSouzaAbreu** [comment] 2022-01-11 02:22
@anburocky3 could we discuss some ideas elsewhere ?

I've been thinking about a second table component designed specifically to work
with Laravel API. So far, my idea was that, just by providing the API's URL,
the component should figure out how to fetch and show data on the table, using
the Laravel's interface.

We could discuss it by mail, or by another platform like Matrix, Briar, or
Telegram. Let me know if you can. Otherwise, it will be just myself thinking

**Comment by Asinging** [comment] 2022-03-05 03:15
why you are trying to build a different table plugin for laravel, i have been able to fix myself with using laravel pagination json data with that datatable extracting the meta and link properties of the json data return from server and harnessing the power of the "isLastPage"  props of the datatable. Now i have an issue, the issue is that there is no visual indication if the  datatable is for the server for more records when it resolve 'isLastpage" to true. my suggestion is that, there should be some sort of slot or any props that one can infuse  to the datatable for loading indication. this should actually ba feature request. thanks

**Comment by AndreSouzaAbreu** [comment] 2022-03-05 15:51
> why you are trying to build a different table plugin for laravel, i have been
> able to fix myself with using laravel pagination JSON data with that
> datatable extracting the meta and link properties of the json data return
> from server and harnessing the power of the "isLastPage" props of the
> datatable. Now i have an issue, the issue is that there is no visual
> indication if the datatable is waiting for the server for more records when
> it resolve 'isLastpage" to true. my suggestion is that, there should be some
> sort of vue named slot or any props that one can infuse to the datatable for
> loading indication. this should actually be feature request. thanks

That is actually a very good idea and it's not hard to implement. I can add a
prop called "LoadingComponent: Object", which is the component to render when
data is loading, and "isLoading: boolean" which tells if data has been loaded
or not. I think I'm do it this week

**Comment by Asinging** [comment] 2022-03-10 02:37
Nice, when that is done alert me please

**Comment by Asinging** [comment] 2022-03-10 02:38
> e

swift move, i love to implement it immediately when you are done let me know please

**Comment by Asinging** [comment] 2022-03-10 02:40
> That is actually a very good idea and it's not hard to implement. I can add a
prop called "LoadingComponent: Object", which is the component to render when
data is loading, and "isLoading: boolean" which tells if data has been loaded
or not. I think I'm do it this week

swift move, i love to implement it immediately when you are done let me know please

**Comment by Asinging** [comment] 2022-03-10 02:47
> That is actually a very good idea and it's not hard to implement. I can add a
> prop called "LoadingComponent: Object", which is the component to render when
> data is loading, and "isLoading: boolean" which tells if data has been loaded
> or not. I think I'm do it this week

if the filter by search query string is expose either as a props or anything of sort, that will be good also so one can search the database when the search for record in the available local server is not found

**Comment by AndreSouzaAbreu** [comment] 2022-03-27 13:52
> > That is actually a very good idea and it's not hard to implement. I can add a
> > prop called "LoadingComponent: Object", which is the component to render when
> > data is loading, and "isLoading: boolean" which tells if data has been loaded
> > or not. I think I'm do it this week
> 
> swift move, i love to implement it immediately when you are done let me know please

I just implemented it today. You can check out the latest release, 3.3.2

**Comment by AndreSouzaAbreu** [comment] 2022-03-27 13:55
Just an update: I'll surely try to make it compatible with Laravel Pagination
API because I myself use Laravel along with VueJS.

It may take a while though (some weeks or months maybe), because I have other
projects to focus now

**Comment by Asinging** [comment] 2022-03-27 23:04
> Just an update: I'll surely try to make it compatible with Laravel Pagination API because I myself use Laravel along with VueJS.
> 
> It may take a while though (some weeks or months maybe), because I have other projects to focus now

Nice, one more issue about this loading and pagination, if you can expose the filter by search query string, it will be great, so one can search the server

**Comment by Asinging** [comment] 2022-03-27 23:05
> Just an update: I'll surely try to make it compatible with Laravel Pagination API because I myself use Laravel along with VueJS.
> 
> It may take a while though (some weeks or months maybe), because I have other projects to focus now

nice work already

**Comment by uwla** [comment] 2023-06-10 13:51
I just want to notice that I still intend to make this plugin compatible with Laravel Pagination API. It has been over a year, but the project is not abandoned; I just have been focused on other things.

**Comment by Reached** [comment] 2023-10-24 07:33
@uwla any updates on this? :)

**Comment by uwla** [comment] 2023-10-24 16:43
Yes. As soon as I get the Vue3 branch working, I'll add SSR support and Laravel Pagination API compatibility.

Checkout the new branch: https://github.com/uwla/vue-data-table/tree/vue3

It has more features than the master, which is for Vue2.

I got a bug in vue3 branch, which should be soon fixed

**Comment by Reached** [comment] 2023-10-30 13:52
Sounds good, thanks for providing this!

**Comment by uwla** [comment] 2023-10-30 18:58
I appreciate your message.
Since Vue3 branch has been released, the roadmap is:

1. provide `ALL entries` option for pagination
2. add support for Laravel pagination API

So, the feature will be included in a few weeks if everything goes right.

**Comment by uwla** [comment] 2024-09-17 13:17
I have been busy with severral other projects,
but I love Laravel, so I want to make this feature works.
Suggestions and help are welcome.

Are you guys @Reached @Asinging @anburocky3  still using this plugin? I have made several improvements and features since this issue was opened, but have not **yet** added support for Laravel pagination.

**Comment by Asinging** [comment] 2024-09-18 10:16
I believe it should be compatible with laravel, i don't write Laravel
though but am still using it, and very helpful

**Comment by uwla** [comment] 2024-12-05 20:02
@anburocky3 @Asinging this plugin now does support Laravel's pagination API.

See [async data section](https://github.com/uwla/vue-data-table?tab=readme-ov-file#async-data) in the README.

It will automatically fetch the data from Laravel, updating the pages accordingly. It will search and sort the data if you use Spatie's Laravel Query Builder along with Laravel.

:)

**Closed by uwla** 2024-12-05 20:02 UTC
Labels: enhancement
